# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy VitePress site to Pages

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [main]
    

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
          # 拉取代码
          - name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          # 安装 pnpm
          - name: Install pnpm
            uses: pnpm/action-setup@v3
            with:
              version: 8

          # 设置 node 版本
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'pnpm'

          # 打包静态文件
          - name: pnpm install
            env:
              APP_BASE_PATH: /${{ github.repository }}
            run: pnpm install && pnpm run
        # build the project
        
          - name: Build
            env:
              APP_BASE_PATH: /${{ github.repository }}
            run: pnpm run build
        # deploy
          - name: Deploy
            uses: JamesIves/github-pages-deploy-action@releases/v4
            with:
               GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}
               BRANCH: gh-pages
               FOLDER: ./dist
          

